global:
  scrape_interval:     60s
  scrape_timeout:      50s
scrape_configs:
  - job_name: 'purestorage-fb'
    metrics_path: /metrics/array
    authorization:
      credentials: T-96ddd476-847c-43a4-a2e3-c9882a1e1c14
    params:
      endpoint: ['10.21.200.19']

    static_configs:
    - targets:
      - pure-fb-om-exporter:9491
      labels:
        location: US
        site: PureTEC
        instance: sn1-fb-c07-19
        env: 'FSA Lab'

  - job_name: 'purestorage-fb_clients'
    metrics_path: /metrics/clients
    authorization:
      credentials: T-96ddd476-847c-43a4-a2e3-c9882a1e1c14
    params:
      endpoint: ['10.21.200.19']

    static_configs:
    - targets:
      - pure-fb-om-exporter:9491
      labels:
        location: US
        site: PureTEC
        instance: sn1-fb-c07-19
        env: 'FSA Lab'

  - job_name: 'purestorage-fb_usage'
    metrics_path: /metrics/usage
    authorization:
      credentials: T-96ddd476-847c-43a4-a2e3-c9882a1e1c14
    params:
      endpoint: ['10.21.200.19']

    static_configs:
    - targets:
      - pure-fb-om-exporter:9491
      labels:
        location: US
        site: PureTEC
        instance: sn1-fb-c07-19
        env: 'FSA Lab'

  - job_name: 'purestorage-fb_policies'
    metrics_path: /metrics/policies
    authorization:
      credentials: T-96ddd476-847c-43a4-a2e3-c9882a1e1c14
    params:
      endpoint: ['10.21.200.19']

    static_configs:
    - targets:
      - pure-fb-om-exporter:9491
      labels:
        location: US
        site: PureTEC
        instance: sn1-fb-c07-19
        env: 'FSA Lab'

  - job_name: 'purestorage-fa'
    metrics_path: /metrics/array?namespace=purefa
    tls_config:
      insecure_skip_verify: true
    scheme: https
    authorization:
      credentials: f583e773-8d10-688f-b57b-024be8a0a089

    static_configs:
    - targets:
      - 10.21.200.161
      labels:
        location: US
        site: PureTEC
        instance: sn1-x50r2-f07-30
        env: 'FSA Lab'

  - job_name: 'purestorage-fa_volumes'
    metrics_path: /metrics/volumes?namespace=purefa
    tls_config:
      insecure_skip_verify: true
    scheme: https
    authorization:
      credentials: f583e773-8d10-688f-b57b-024be8a0a089

    static_configs:
    - targets:
      - 10.21.200.161
      labels:
        location: US
        site: PureTEC
        instance: sn1-x50r2-f07-30
        env: 'FSA Lab'

  - job_name: 'purestorage-fa_hosts'
    metrics_path: /metrics/hosts?namespace=purefa
    tls_config:
      insecure_skip_verify: true
    scheme: https
    authorization:
      credentials: f583e773-8d10-688f-b57b-024be8a0a089

    static_configs:
    - targets:
      - 10.21.200.161
      labels:
        location: US
        site: PureTEC
        instance: sn1-x50r2-f07-30
        env: 'FSA Lab'

  - job_name: 'purestorage-fa_pods'
    metrics_path: /metrics/pods?namespace=purefa
    tls_config:
      insecure_skip_verify: true
    scheme: https
    authorization:
      credentials: f583e773-8d10-688f-b57b-024be8a0a089

    static_configs:
    - targets:
      - 10.21.200.161
      labels:
        location: US
        site: PureTEC
        instance: sn1-x50r2-f07-30
        env: 'FSA Lab'

  - job_name: 'purestorage-fa_directories'
    metrics_path: /metrics/directories?namespace=purefa
    tls_config:
      insecure_skip_verify: true
    scheme: https
    authorization:
      credentials: f583e773-8d10-688f-b57b-024be8a0a089

    static_configs:
    - targets:
      - 10.21.200.161
      labels:
        location: US
        site: PureTEC
        instance: sn1-x50r2-f07-30
        env: 'FSA Lab'

